/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-08-12 11:18:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.aoplog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class submit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>提交新日志</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link href=\"/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/dist/css/bootstrap-select.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"/aoplog/submit\"><font\r\n");
      out.write("\t\t\t\t\t\t\tsize=\"+3\">新建log</font></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/aoplog/listloginfosimple\"><font size=\"+3\">已建日志</font></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div><label class=\"col-sm-2 control-label\" >用户：<a href=\"/userinfo/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user['username']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user[\"name\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a></label></div>\r\n");
      out.write("\t\t \t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<!--------------------------------------------------台头 --------------------------------------------------------->\r\n");
      out.write("\t<form action=\"/aoplog/doaction\" method=\"post\">\r\n");
      out.write("\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><font size=\"+3\">JIRA</font></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("                  <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">主题*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='aoplog.summary' placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.summary}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${summaryErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("                  <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">经办人<span style=\"color: red\">**</span></label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t   <select class=\"selectpicker show-tick\" data-size=\"5\" id=\"assignee\" name=\"aoplog.assignee\">\r\n");
      out.write("\t\t\t\t\t<option class=\"default-option\" value=\"shiwei\">施威</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"linghongbo\">宏博</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"fujie\">傅杰</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"luxueyu\">卢学裕</option>\r\n");
      out.write("\t\t\t\t  </select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">日志名称*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='aoplog.logname' placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.logname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lognameErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">日志代号*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='aoplog.logid' placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.logid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${logidErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">日志版本*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='aoplog.version' placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${versionErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">Wiki地址*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='aoplog.wikihttp' placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.wikihttp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wikihttpErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">WikiIdex位置*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='aoplog.wikiindex' placeholder=\"前一个标题名称|当前标题名称\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.wikiindex}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wikiindexErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">重要级别 <span style=\"color: red\">**</span></label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t   <label>\r\n");
      out.write("                   <input type=\"radio\" name=\"aoplog.level\" value=\"11710\" checked> 高 （运营主要日志）\r\n");
      out.write("                  </label>\r\n");
      out.write("                   <label>\r\n");
      out.write("                   <input type=\"radio\" name=\"aoplog.level\" value=\"11711\" checked> 中（服务运行日志）\r\n");
      out.write("                  </label>\r\n");
      out.write("                   <label>\r\n");
      out.write("                   <input type=\"radio\" name=\"aoplog.level\" value=\"11712\" checked> 低 （测试，错误，性能，研究）\r\n");
      out.write("                  </label>\r\n");
      out.write("                  <span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${levelErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">日志分片规则</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='aoplog.splitrule'  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.splitrule}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">来源团队 <span style=\"color: red\">**</span></label>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("                <select class=\"selectpicker show-tick\" data-size=\"5\" id=\"customfield_11483\" name=\"aoplog.team\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"default-option\" value=\"\">Please select...</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"default-option\" value=\"-1\">None</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11513\" value=\"11713\">优酷主站前端</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11514\" value=\"11714\">优酷主站后台</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11515\" value=\"11715\">搜酷</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11516\" value=\"11716\">客户端</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11517\" value=\"11717\">无线</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11768\" value=\"11768\">大数据开发</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11856\" value=\"11856\">娱乐互动</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("                <select class=\"selectpicker show-tick\" data-size=\"5\" id=\"customfield_11483:1\" name=\"aoplog.team\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"default-option\" value=\"\">Please select...</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"default-option\" value=\"-1\">None</option>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"优酷主站前端\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11513\" value=\"11718\">优酷主站前端:cms</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11513\" value=\"11719\">优酷主站前端:wap</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11513\" value=\"11720\">优酷主站前端:播放页</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11513\" value=\"11721\">优酷主站前端:用户中心</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"优酷主站后台\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11514\" value=\"11722\">优酷主站后台:播放器</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11514\" value=\"11723\">优酷主站后台:中间层</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"搜酷\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11515\" value=\"11724\">搜酷:全网</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11515\" value=\"11725\">搜酷:优酷站内</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11515\" value=\"11726\">搜酷:土豆站内</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"客户端\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11516\" value=\"11727\">客户端:iku</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11516\" value=\"11728\">客户端:itudou</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"无线\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11517\" value=\"11729\">无线:app</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11517\" value=\"11730\">无线:接口</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"大数据开发\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11768\" value=\"11769\">大数据开发：推荐构架</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"娱乐互动\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11857\" value=\"11857\">互动娱乐：星梦网站</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t</select><span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${teamErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">采集接口服务类型 <span style=\"color: red\">**</span></label>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("                <select class=\"selectpicker show-tick\" data-size=\"5\" id=\"customfield_11508\" name=\"aoplog.servicetype\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"default-option\" value=\"\">Please select...</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"default-option\" value=\"-1\">None</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11544\" value=\"11742\">http日志采集服务短接口</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11545\" value=\"11743\">http日志采集服务长接口</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11546\" value=\"11744\">collector日志收集服务</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("                <select class=\"selectpicker show-tick\" data-size=\"5\" id=\"customfield_11508:1\" name=\"aoplog.servicetype\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"default-option\" value=\"\">Please select...</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"default-option\" value=\"-1\">None</option>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"http日志采集服务短接口\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11544\" value=\"11745\">短接口:一级域名：保留cookie(youku.com)</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11544\" value=\"11746\">短接口:一级域名：不保留cookie(ykimg.com)</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11544\" value=\"11747\">短接口:二级域名：页面p.l</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11544\" value=\"11748\">短接口:二级域名：播放v.l</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11544\" value=\"11749\">短接口:二级域名：时长t.l</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11544\" value=\"11750\">短接口:二级域名：心跳p-log</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11544\" value=\"11751\">短接口:二级域名：推荐r.l</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"http日志采集服务长接口\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11545\" value=\"11752\">长接口:一级域名：保留cookie(youku.com)</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11545\" value=\"11753\">长接口:一级域名：不保留cookie(ykimg.com)</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11545\" value=\"11754\">长接口:二级域名：页面p.l</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11545\" value=\"11755\">长接口:二级域名：播放v.l</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11545\" value=\"11756\">长接口:二级域名：时长t.l</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11545\" value=\"11757\">长接口:二级域名：推荐r.l</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11545\" value=\"11758\">长接口:二级域名：心跳p-log</option>\r\n");
      out.write("                        </optgroup>\r\n");
      out.write("                        <optgroup label=\"collector日志收集服务\">\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11546\" value=\"11759\">collector日志收集服务:udp协议</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11546\" value=\"11760\">collector日志收集服务:log4j jar包</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11546\" value=\"11761\">collector日志收集服务:python程序</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11546\" value=\"11762\">collector日志收集服务:c程序</option>\r\n");
      out.write("\t\t\t\t\t\t<option class=\"option-group-11744\" value=\"11810\">collector日志收集服务:tail方式</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t</select><span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${servicetypeErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">采集接口上线步骤 <span style=\"color: red\">**</span></label>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t   <label>\r\n");
      out.write("                   <input type=\"radio\" name=\"aoplog.onlinestep\" value=\"11733\" checked> 根据wiki配置http接收 \r\n");
      out.write("                  </label>\r\n");
      out.write("                   <label>\r\n");
      out.write("                   <input type=\"radio\" name=\"aoplog.onlinestep\" value=\"11734\" checked> collector配置接收日志代号\r\n");
      out.write("                  </label>\r\n");
      out.write("                  <span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${onlinestepErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">采集机房<span style=\"color: red\">**</span></label>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t   <label>\r\n");
      out.write("                   <input type=\"checkbox\" name=\"aoplog.room\" value=\"bj\" checked> 北京集群\r\n");
      out.write("                  </label>\r\n");
      out.write("                   <label>\r\n");
      out.write("                   <input type=\"checkbox\" name=\"aoplog.room\" value=\"sh\" checked> 上海集群\r\n");
      out.write("                  </label>\r\n");
      out.write("                   <label>\r\n");
      out.write("                   <input type=\"checkbox\" name=\"aoplog.room\" value=\"wh\" checked> 武汉集群\r\n");
      out.write("                  </label>\r\n");
      out.write("                   <label>\r\n");
      out.write("                   <input type=\"checkbox\" name=\"aoplog.room\" value=\"gd\" checked> 广东集群\r\n");
      out.write("                  </label>\r\n");
      out.write("                   <label>\r\n");
      out.write("                   <input type=\"checkbox\" name=\"aoplog.room\" value=\"qd\" checked> 青岛集群\r\n");
      out.write("                  </label>\r\n");
      out.write("                  <span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${onlinestepErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">升级变更目的*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='aoplog.aim' placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.aim}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aimErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t               <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">原始日志保留时长 <span style=\"color: red\">**</span></label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t   <select class=\"selectpicker show-tick\" data-size=\"5\" name=\"aoplog.keeptime\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"-1\">None</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11735\">一周</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11736\">一个月</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11737\">三个月</option>\r\n");
      out.write("\t\t\t\t   </select>\r\n");
      out.write("\t\t\t\t   <span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keeptimeErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">hdfs存储是否压缩 <span style=\"color: red\">**</span></label>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t   <label>\r\n");
      out.write("                   <input type=\"radio\" name=\"aoplog.compression\" value=\"11738\" checked> 压缩\r\n");
      out.write("                  </label>\r\n");
      out.write("                   <label>\r\n");
      out.write("                   <input type=\"radio\" name=\"aoplog.compression\" value=\"11739\" checked> 不压缩\r\n");
      out.write("                  </label>\r\n");
      out.write("                  <span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${compressionErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">hdfs存储路径*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='aoplog.hdfspath' id=\"jhdfspath\" placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.hdfspath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" onchange=\"jhdfspathchange(this)\">\r\n");
      out.write("\t\t\t       <span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hdfspathErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">配置logdata压缩 <span style=\"color: red\">**</span></label>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t   <label>\r\n");
      out.write("                   <input type=\"radio\" name=\"aoplog.logcompression\" value=\"11740\" checked> 是\r\n");
      out.write("                  </label>\r\n");
      out.write("                   <label>\r\n");
      out.write("                   <input type=\"radio\" name=\"aoplog.logcompression\" value=\"11741\" checked> 否\r\n");
      out.write("                  </label>\r\n");
      out.write("                  <span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${logcompressionErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">hive表*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='aoplog.hivetable' id=\"jhivetable\" placeholder=\"表之间用';'隔开 如：表名1;表名2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.hivetable}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" onchange=\"jhtchange(this)\">\r\n");
      out.write("\t\t\t       <span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hivetableErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">转发规则*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t      <textarea name='aoplog.rule' class=\"form-control\" rows=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.rule}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\t\t\t      <span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ruleErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">风险评估*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t      <textarea name='aoplog.risk' class=\"form-control\" rows=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.risk}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\t\t\t      <span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${riskErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">回滚步骤及紧急停止采集方法*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t      <textarea name='aoplog.method' class=\"form-control\" rows=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aoplog.method}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\t\t\t      <span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${methodErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("        <hr>\r\n");
      out.write("\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><font size=\"+3\">WIKI</font></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">上线时间*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='wiki.onlinetime' placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wiki.onlinetime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" onkeyup=\"this.value=this.value.replace(/\\D/g,'')\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${onlinetimeErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">分隔符*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='wiki.separator' placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wiki.separator}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${separatorErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">存放路径*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='wiki.path' id=\"whdfspath\" placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wiki.path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" onchange=\"whdfspathchange(this)\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pathErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">hive表名*</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='wiki.tablename' id=\"whivetable\" placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wiki.tablename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" onchange=\"whtchange(this)\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tablenameErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">上版差异</label>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" style=\"float:left;width: 800px;\" name='wiki.diff' placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wiki.diff}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t       </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table class=\"table table-striped\" id=\"idTB\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t     <tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t              <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">字段ID*</label>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">参数名称*</label>\r\n");
      out.write("\t\t        </td>\r\n");
      out.write("\t\t        <td>\r\n");
      out.write("\t\t\t\t <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">字段名称</label>\r\n");
      out.write("\t\t        </td>\r\n");
      out.write("\t\t        <td>\r\n");
      out.write("\t\t\t\t <label style=\"float:right;width: 200px;\" class=\"col-sm-2 control-label\">字段类型*</label>\r\n");
      out.write("\t\t        </td>\r\n");
      out.write("\t\t        <td>\r\n");
      out.write("\t\t\t\t <label style=\"float:right;width: 320px;\" class=\"col-sm-2 control-label\">字段解释</label>\r\n");
      out.write("\t\t        </td>\r\n");
      out.write("\t\t        <td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-default\"  onclick=\"addRow()\" >添加一行</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t   </table>\r\n");
      out.write("\t   <hr>\r\n");
      out.write("\t   <table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t    <td>\r\n");
      out.write("\t\t\t       ");
      if (_jspx_meth_c_005fchoose_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t       ");
      if (_jspx_meth_c_005fchoose_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t         ");
      if (_jspx_meth_c_005fchoose_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                 </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("           <script>\r\n");
      out.write("\t\t\t\t\tfunction addRow() {//添加表格的一行\r\n");
      out.write("\t\t\t\t\t\toTR = idTB.insertRow(idTB.rows.length);\r\n");
      out.write("\t\t\t\t\t\ttmpNum = oTR.rowIndex;\r\n");
      out.write("\t\t\t\t\t\toTD1 = oTR.insertCell(0);\r\n");
      out.write("\t\t\t\t\t\toTD2 = oTR.insertCell(1);\r\n");
      out.write("\t\t\t\t\t\toTD3 = oTR.insertCell(2);\r\n");
      out.write("\t\t\t\t\t\toTD4 = oTR.insertCell(3);\r\n");
      out.write("\t\t\t\t\t\toTD5 = oTR.insertCell(4);\r\n");
      out.write("\t\t\t\t\t\toTD6 = oTR.insertCell(5);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\toTD1.innerText = \"第\" + tmpNum + \"行\";//在该处添加的HTML代码会原封不动的显示在页面上\r\n");
      out.write("\t\t\t\t\t\toTD1.innerHTML = \"<input type='text' class='form-control' name='pa.id'>\";//要在该格添加的HTML代码填在这里，因为这里是text，注意不要重名了。\r\n");
      out.write("\t\t\t\t\t\toTD2.innerHTML = \"<input type='text' class='form-control' style='color:#999' name='pa.pname' value='#' onfocus='onf(this)' onblur='onb(this)'>\";\r\n");
      out.write("\t\t\t\t\t\toTD3.innerHTML = \"<input type='text' class='form-control' name='pa.name'>\";\r\n");
      out.write("\t\t\t\t\t\toTD4.innerHTML = \"<input type='text' class='form-control' style='color:#999' name='pa.type' value='String' onfocus='onfString(this)' onblur='onbString(this)'>\";\r\n");
      out.write("\t\t\t\t\t\toTD5.innerHTML = \"<input type='text' class='form-control' style='width: 320px;' name='pa.description'>\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\toTD6.innerHTML = \"<input type='button' class='btn btn-danger' onclick='deltheRow(this)' value='删除'> \";\r\n");
      out.write("\t\t\t\t\t\tidLast.innerText = idTB.rows.length;\r\n");
      out.write("\t\t\t\t\t\tif (idTB.rows.length > 0)\r\n");
      out.write("\t\t\t\t\t\t\tidFirst.innerText = '1';\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction deltheRow(obj) { //参数为A标签对象\r\n");
      out.write("\t\t\t\t\t\tvar row = obj.parentNode.parentNode; //A标签所在行\r\n");
      out.write("\t\t\t\t\t\tvar tb = row.parentNode; //当前表格\r\n");
      out.write("\t\t\t\t\t\tvar rowIndex = row.rowIndex; //A标签所在行下标\r\n");
      out.write("\t\t\t\t\t\ttb.deleteRow(rowIndex); //删除当前行\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction onf(obj) {\r\n");
      out.write("\t\t\t\t\t\tif (obj.value == '#') {\r\n");
      out.write("\t\t\t\t\t\t\tobj.value = '';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tobj.style.color = '#000';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction onb(obj) {\r\n");
      out.write("\t\t\t\t\t\tif (obj.value == '') {\r\n");
      out.write("\t\t\t\t\t\t\tobj.value = '#';\r\n");
      out.write("\t\t\t\t\t\t\tobj.style.color = '#999';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction onfString(obj) {\r\n");
      out.write("\t\t\t\t\t\tif (obj.value == 'String') {\r\n");
      out.write("\t\t\t\t\t\t\tobj.value = '';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tobj.style.color = '#000';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction onbString(obj) {\r\n");
      out.write("\t\t\t\t\t\tif (obj.value == '') {\r\n");
      out.write("\t\t\t\t\t\t\tobj.value = 'String';\r\n");
      out.write("\t\t\t\t\t\t\tobj.style.color = '#999';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfunction jhtchange(obj)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t document.getElementById(\"whivetable\").value=obj.value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfunction whtchange(obj)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t document.getElementById(\"jhivetable\").value=obj.value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfunction jhdfspathchange(obj)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t document.getElementById(\"whdfspath\").value=obj.value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfunction whdfspathchange(obj)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t document.getElementById(\"jhdfspath\").value=obj.value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("<!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("<script src=\"/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/dist/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\r\n");
      out.write("//下拉菜单\r\n");
      out.write("$('.selectpicker').selectpicker({noneSelectedText:'请选择'});\r\n");
      out.write("$('.selectpicker').selectpicker('val',$('.selectpicker').attr('value'));\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t \t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t \t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /aoplog/submit.jsp(29,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user['username']==null||sessionScope.user['username']==''}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t \t  \t\t\t <div class=\"alert alert-danger\" role=\"alert\" style=\"width: 1320px;\">\r\n");
        out.write("                     <strong>Session过期请重新登录</strong>\r\n");
        out.write("         \t\t\t </div>\r\n");
        out.write("\t \t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f1.setParent(null);
    int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
    if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /aoplog/submit.jsp(455,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(pidErrorMessage==''||pidErrorMessage==null)&&(pnameErrorMessage==''||pnameErrorMessage==null)&&(ptypeErrorMessage==''||ptypeErrorMessage==null)}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /aoplog/submit.jsp(458,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(pidErrorMessage!=''&&pidErrorMessage!=null)||(pnameErrorMessage!=''&&pnameErrorMessage!=null)||((ptypeErrorMessage!=''&&ptypeErrorMessage!=null))}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
    if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t<td><span style=\"color: red\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pidErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</span></td>\r\n");
        out.write("\t\t\t\t\t\t<td><span style=\"color: red\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pnameErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</span></td>\r\n");
        out.write("\t\t\t\t\t\t<td></td>\r\n");
        out.write("\t\t\t\t\t\t<td><span style=\"color: red\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ptypeErrorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</span></td>\r\n");
        out.write("\t\t\t\t\t\t<td></td>\r\n");
        out.write("\t\t\t\t\t\t<td></td>\r\n");
        out.write("\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /aoplog/submit.jsp(471,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/aoplog/submit.jsp(471,3) '${palist}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${palist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /aoplog/submit.jsp(471,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("pa");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<tr>\r\n");
          out.write("\t\t\t    <td>\r\n");
          out.write("\t\t\t    <input type=\"text\" class=\"form-control\" name='pa.id' value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pa.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("\t\t\t    </td>\r\n");
          out.write("\t\t\t     <td>\r\n");
          out.write("\t\t\t    <input type=\"text\" class=\"form-control\" name='pa.pname' value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pa.pname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("\t\t\t    </td>\r\n");
          out.write("\t\t\t     <td>\r\n");
          out.write("\t\t\t    <input type=\"text\" class=\"form-control\" name='pa.name' value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pa.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("\t\t\t    </td>\r\n");
          out.write("\t\t\t     <td>\r\n");
          out.write("\t\t\t    <input type=\"text\" class=\"form-control\" name='pa.type' value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pa.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("\t\t\t    </td>\r\n");
          out.write("\t\t\t     <td>\r\n");
          out.write("\t\t\t    <input type=\"text\" class=\"form-control\" name='pa.description' value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pa.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\r\n");
          out.write("\t\t\t    </td>\r\n");
          out.write("\t\t\t    <td>\r\n");
          out.write("\t\t\t     <button type=\"button\" class=\"btn btn-danger\"  onclick='deltheRow(this)'>删除</button>\r\n");
          out.write("\t\t\t    </td>\r\n");
          out.write("\t\t\t</tr>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f2.setParent(null);
    int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
    if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t        ");
        if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t        ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
    // /aoplog/submit.jsp(507,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user['submitwiki']==true}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
    if (_jspx_eval_c_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t          <label>\r\n");
        out.write("                        <input type=\"checkbox\" name=\"action\" value=\"2\" checked> 生成wiki\r\n");
        out.write("                      </label>\r\n");
        out.write("\t\t\t        ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f3 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f3.setParent(null);
    int _jspx_eval_c_005fchoose_005f3 = _jspx_th_c_005fchoose_005f3.doStartTag();
    if (_jspx_eval_c_005fchoose_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t        ");
        if (_jspx_meth_c_005fwhen_005f4(_jspx_th_c_005fchoose_005f3, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t        ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f4 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f3);
    // /aoplog/submit.jsp(514,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user['submitjira']==true}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f4 = _jspx_th_c_005fwhen_005f4.doStartTag();
    if (_jspx_eval_c_005fwhen_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t           <label>\r\n");
        out.write("                         <input type=\"checkbox\" name=\"action\" value=\"3\" checked> 生成jira\r\n");
        out.write("                       </label>\r\n");
        out.write("\t\t\t        ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f4 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f4.setParent(null);
    int _jspx_eval_c_005fchoose_005f4 = _jspx_th_c_005fchoose_005f4.doStartTag();
    if (_jspx_eval_c_005fchoose_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                     ");
        if (_jspx_meth_c_005fwhen_005f5(_jspx_th_c_005fchoose_005f4, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t    ");
        if (_jspx_meth_c_005fwhen_005f6(_jspx_th_c_005fchoose_005f4, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                  ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f5 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f4);
    // /aoplog/submit.jsp(521,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user['submitwiki']==false&&sessionScope.user['submitjira']==false}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f5 = _jspx_th_c_005fwhen_005f5.doStartTag();
    if (_jspx_eval_c_005fwhen_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t        <button type=\"submit\" class=\"btn btn-primary disabled\" >提交</button> \r\n");
        out.write("\t\t\t\t    ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f6 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f4);
    // /aoplog/submit.jsp(524,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user['submitwiki']==true||sessionScope.user['submitjira']==true}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f6 = _jspx_th_c_005fwhen_005f6.doStartTag();
    if (_jspx_eval_c_005fwhen_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t        <button type=\"submit\" class=\"btn btn-primary\" >提交</button> \r\n");
        out.write("\t\t\t\t    ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f6.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f6);
    return false;
  }
}
