/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-02 03:58:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.youku.dpm.utils.BasePathUtil;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

	response.setHeader("Pragma","No-cache"); 
	response.setHeader("Cache-Control","no-cache"); 
	response.setDateHeader("Expires", 0); 
	String basePath = BasePathUtil.getBasePath(request);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link href=\"sso/css/jquery-ui-1.8.13.custom.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"sso/js/jquery.js\"></script>\r\n");
      out.write("<script src=\"sso/js/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/images/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/common/images/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<title>优酷土豆数据平台</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* css reset */\r\n");
      out.write("/** 清除内外边距 **/\r\n");
      out.write("body, h1, h2, h3, h4, h5, h6, hr, p, blockquote, /* structural elements 结构元素 */\r\n");
      out.write("dl, dt, dd, ul, ol, li, /* list elements 列表元素 */\r\n");
      out.write("pre, /* text formatting elements 文本格式元素 */\r\n");
      out.write("form, fieldset, legend, button, input, textarea, /* form elements 表单元素 */\r\n");
      out.write("th, td /* table elements 表格元素 */\r\n");
      out.write("{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("/** 设置默认字体 **/\r\n");
      out.write("body,\r\n");
      out.write("button, input, select, textarea /* for ie */\r\n");
      out.write("{\r\n");
      out.write("    font: 12px/1 Tahoma, Helvetica, Arial, \"\\5b8b\\4f53\", sans-serif; /* 用 ascii 字符表示，使得在任何编码下都无问题 */\r\n");
      out.write("}\r\n");
      out.write("/** 重置列表元素 **/\r\n");
      out.write("ul, ol {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write("/** 重置文本格式元素 **/\r\n");
      out.write("a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:hover {\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("/** 重置表单元素 **/\r\n");
      out.write("legend {\r\n");
      out.write("    color: #000;\r\n");
      out.write("}\r\n");
      out.write("/* for ie6 */\r\n");
      out.write("fieldset, img {\r\n");
      out.write("    border: 0;\r\n");
      out.write("}\r\n");
      out.write("/* img 搭车：让链接里的 img 无边框 */\r\n");
      out.write("button, input, select, textarea {\r\n");
      out.write("    font-size: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* main */\r\n");
      out.write("body {\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    color: #000000;\r\n");
      out.write("    line-height: 150%;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    width: 98%;\r\n");
      out.write("}\r\n");
      out.write("img {\r\n");
      out.write("    border: 0;\r\n");
      out.write("}\r\n");
      out.write("ul li {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write("a:link, a:visited {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #077ac7;\r\n");
      out.write("}\r\n");
      out.write("a:hover, a:active {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*表单相关*/\r\n");
      out.write("input, textarea, select, button {\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    padding: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("    overflow: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    border: 1px solid #DCDCDC;\r\n");
      out.write("    padding-left: 2px;\r\n");
      out.write("    background: #fff url(sso/images/form_blue.gif) repeat-x top left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*按钮样式*/\r\n");
      out.write(".button_style {\r\n");
      out.write("    background: url(sso/images/btn_bg.gif) repeat-x 0 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border: 1px solid #9CC9E0;\r\n");
      out.write("    padding: 4px 6px;\r\n");
      out.write("    *padding: 0px 3px;\r\n");
      out.write("    margin: 2px;\r\n");
      out.write("    color: #077ac7;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write(".button_style:hover {\r\n");
      out.write("    background: #077AC7;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 本页面专用 */\r\n");
      out.write(".loginWarp {\r\n");
      out.write("    width: 500px;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin: 120px auto auto;\r\n");
      out.write("    padding: 10px 10px 10px 10px;\r\n");
      out.write("}\r\n");
      out.write(".loginWarp .top{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".loginWarp .bd {\r\n");
      out.write("    padding: 10px 0px 10px 50px;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("}\r\n");
      out.write(".loginWarp .bd tr{ height: 30px; }\r\n");
      out.write(".loginWarp .bd .col1{ width: 50px; }\r\n");
      out.write(".loginWarp .bd .col2{ width: 300px;}\r\n");
      out.write(".loginWarp .bd .col2 input{ width: 275px; }\r\n");
      out.write(".loginWarp .bottom{ text-align: center; line-height: 40px; margin-top:10px;}\r\n");
      out.write(".loginWarp .tip{background:#ECFF0F;display:none;font-weight:bold;opactity:0.7;left:650px;position:absolute;text-align:center;top:-100px;padding:20px;width:200px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onkeydown=\"keyLogin();\">\r\n");
      out.write("<div class = \"loginWarp\">\r\n");
      out.write("\t<div id=\"tip\" class=\"tip\"></div>\r\n");
      out.write("    <div class = \"top\">\r\n");
      out.write("\t<!--<img src=\"sso/images/youkulogo.png\"/>-->\r\n");
      out.write("\t<img src=\"sso/images/yt.jpg\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"tabs\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t    <li id=\"li1\"><a href=\"#tb1\">用户登陆</a></li>\r\n");
      out.write("\t    <!--<li id=\"li2\"><a href=\"#tb2\">密码用户登陆</a></li>-->\r\n");
      out.write("\t    <li id=\"li3\"><a href=\"#tb3\">访问帮助</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<div id=\"tb1\" class=\"bd\">\r\n");
      out.write("\t    <div id=\"prompt\"><!-- prompt --></div>\r\n");
      out.write("\t    <form id=\"system_login_form1\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"col1\">用户名: </td>\r\n");
      out.write("\t\t\t\t<td class=\"col2\"><input type=\"text\" id = \"username\" name = \"username\" value = \"\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"col1\" id=\"sign\">密码: </td>\r\n");
      out.write("\t\t\t\t<td class=\"col2\" id=\"signVal\"><input type=\"password\" id = \"password\" name = \"password\" value = \"\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" style=\"text-align:center;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"btn-login\" class=\"button_style\" value = \"登陆\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" class=\"button_style\" id=\"getCode\" value = \"重置\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<a id=\"forget\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/monitor/user/getPasswd.jsp\"><font color=\"red\">忘记密码?</font</a>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<a id=\"reg\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/monitor/user/usereg.jsp\"><font color=\"red\">注册</font></a>\r\n");
      out.write("\t    </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"tb3\" class=\"bd\">\r\n");
      out.write("\t    <p>1. 用户登陆请先绑定公司信箱</p>\r\n");
      out.write("\t    <p>2. <a href=\"http://a001.namenode.hadoop.qingdao.youku:50070/\" id=\"back\">DFS信息访问入口</a></p>\r\n");
      out.write("    \t<p>3. <a href=\"http://a001.jobtracker.hadoop.qingdao.youku:50030/\" id=\"back\">JOB信息访问入口</a></p>\r\n");
      out.write("    \t<p>4. <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/hostlist.jsp\" id=\"back\">本机hosts配置信息</a></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"bottom\">Copyright © 2013 youku.com Inc. </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"text-align: center;color:red;\">为了您更好的使用，请使用IE8以上浏览器或火狐,Chrome</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    $(function() {\r\n");
      out.write("    $(\"#username\").focus();\r\n");
      out.write("\t\t// 初始化tab\r\n");
      out.write("\t\t$( \"#tabs\" ).tabs();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(top.location != self.location) {\r\n");
      out.write("\t\t\ttop.location = self.location;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar ajaxReq = function(params) {\r\n");
      out.write("\t\t\tvar tip = '';\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"");
      out.print(basePath);
      out.write("userManager/login\", \r\n");
      out.write("\t\t\t\tdata:params, \r\n");
      out.write("\t\t\t\tsuccess:function(msg){\r\n");
      out.write("\t\t\t\t\tvar loginCode = msg;\r\n");
      out.write("\t\t\t\t\tif(loginCode== '-1'){\r\n");
      out.write("     \t\t\t\t\ttip = \"密码不正确\";\r\n");
      out.write("  \t\t\t\t\t}else if(loginCode== '-2'){\r\n");
      out.write("  \t\t\t\t\t\ttip = \"用户未激活\";\r\n");
      out.write("  \t\t\t\t\t}else if(loginCode== '-3'){\r\n");
      out.write("     \t\t\t\t\ttip = \"用户未注册\";\r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(tip != '') {\r\n");
      out.write("\t\t\t\t\t\t$(\"#tip\").html(tip).slideDown();\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$(\"#tip\").css(\"display\", \"none\").html(\"登陆成功!<br/>2秒后即将自动跳转\").slideDown();\r\n");
      out.write("\t\t\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href = \"");
      out.print(basePath);
      out.write("index.jsp\";\r\n");
      out.write("\t\t\t\t\t\t}, 2000);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//重置\r\n");
      out.write("\t\t$(\"#getCode\").click(function(){\r\n");
      out.write("\t\t\t$(\"#username\").attr(\"value\",'');\r\n");
      out.write("\t\t\t$(\"#password\").attr(\"value\",'');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//正常方式登陆\r\n");
      out.write("\t\t$(\"#btn-login\").click(function(){\r\n");
      out.write("\t\t\tvar username = $(\"#username\").val();\r\n");
      out.write("\t\t\tvar pwd = $(\"#password\").val();\r\n");
      out.write("\t\t\tif($.trim(username) == \"\" || $.trim(pwd) == \"\") {\r\n");
      out.write("\t\t\t\t$(\"#tip\").css(\"display\", \"none\").html(\"请输入用户名和密码！\").slideDown();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tajaxReq({username:username, password:pwd});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction keyLogin(){\r\n");
      out.write("\t\t\tif (event.keyCode==13){//回车键的键值为13\r\n");
      out.write("\t\t\t\t$(\"#btn-login\").click();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
