/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-02 04:01:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.monitor.storm;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.youku.dpm.utils.BasePathUtil;

public final class submitTop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/inc/head.jsp", Long.valueOf(1366282878000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	response.setHeader("Cache-Control", "max-age=0");
	String path = request.getContextPath();
	String basePath = BasePathUtil.getBasePath(request);

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write('\r');
      out.write('\n');
      out.write(' ');
String basePath_head = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
 	String version = basePath_head+"version";
    
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<LINK href=\"");
      out.print(basePath_head);
      out.write("common/css/admin.css\" type=\"text/css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\t<LINK href=\"");
      out.print(basePath_head);
      out.write("common/css/fenye.css\" type=\"text/css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<LINK href=\"");
      out.print(basePath_head);
      out.write("common/css/css.css\" type=\"text/css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\t\t<LINK href=\"");
      out.print(basePath_head);
      out.write("common/css/dialog.css\" type=\"text/css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(basePath_head);
      out.write("common/images/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(basePath_head);
      out.write("common/images/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/jquery.min.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/jquery.form.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/jquery.validate.min.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/messages_cn.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/application.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/lang/zh-cn.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/WdatePicker.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/artDialog.js\" ></script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/iframeTools.js\" ></script>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/fancybox/jquery.mousewheel-3.0.2.pack.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/fancybox/jquery.fancybox-1.3.1.js\" ></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath_head);
      out.write("common/js/fancybox/jquery.fancybox-1.3.1.css\" media=\"screen\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath_head);
      out.write("common/js/json2.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"STYLESHEET\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("common/css/main.css\" />\r\n");
      out.write("<title>Storm作业提交 </title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tvar msg = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\tif(msg != '' && msg !=null) {\r\n");
      out.write("\t\t\talert(msg)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction apply() {\r\n");
      out.write("\t\tvar topName = $(\"#topName\").val();\r\n");
      out.write("\t\tvar className = $(\"#className\").val();\r\n");
      out.write("\t\tvar clusterId = $(\"#clusterId\").val();\r\n");
      out.write("\t\tvar workNum = $(\"#workNum\").val();\r\n");
      out.write("\t\tvar topFile = $(\"#topFile\").val();\r\n");
      out.write("\t\tif(topName == '' || topName == null || typeof(topName) == 'undefined'){\r\n");
      out.write("\t\t\talert('请输入作业名')\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(className == '' || className == null || typeof(className) == 'undefined'){\r\n");
      out.write("\t\t\talert('请输入全类名')\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(workNum == '' || workNum == null || typeof(workNum) == 'undefined'){\r\n");
      out.write("\t\t\talert('请输入初始worker数')\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar reg = new RegExp(\"^[0-9]*$\");// 数组校验\r\n");
      out.write("\t\tif(!reg.test(workNum)) {\r\n");
      out.write("\t\t\talert('worker数必须为数字')\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(topFile == '' || topFile == null || typeof(topFile) == 'undefined'){\r\n");
      out.write("\t\t\talert('请选择要上传的作业文件')\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#myform\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<TABLE cellSpacing=0 cellPadding=0 width=\"100%\" align=center border=0>\r\n");
      out.write("\t\t\t<TR height=28>\r\n");
      out.write("\t\t\t\t<TD background=\"");
      out.print(basePath );
      out.write("common/images/title_bg1.jpg\">\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;当前位置: 首页&gt;&gt;Storm作业管理&gt;&gt;\r\n");
      out.write("\t\t\t\t\tStorm作业提交\t\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t<td width=\"50%\" background=\"");
      out.print(basePath );
      out.write("common/images/title_bg1.jpg\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td background=\"");
      out.print(basePath );
      out.write("common/images/title_bg1.jpg\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD bgColor=\"#b1ceef\" height=\"1\" colspan=\"3\"></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR height=\"20\">\r\n");
      out.write("\t\t\t\t<TD background=\"");
      out.print(basePath );
      out.write("common/images/shadow_bg.jpg\" colspan=\"3\"></TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("\t\t\r\n");
      out.write("<form  id=\"myform\"   action=\"");
      out.print(basePath);
      out.write("stormManager/upload\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"50%\" align=\"center\" border=\"0\">\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr>\r\n");
      out.write("\t\t<th class=\"form_head\" align=\"center\" colspan=\"2\">作业提交</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td class=\"td_x_bg\">作业名称:</td><td class=\"td_bg\"><input id=\"topName\" maxlength=\"20\" type=\"text\" name=\"topName\"  value=\"\"/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr> \r\n");
      out.write("<td class=\"td_x_bg\">全类名:</td><td class=\"td_bg\"> <input id=\"className\" maxlength=\"40\" type=\"text\" name=\"className\"  value=\"\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td class=\"td_x_bg\">集群:</td><td class=\"td_bg\"> \r\n");
      out.write("\t<select id=\"clusterId\" name=\"clusterId\">\r\n");
      out.write("\t\t<option value=\"QD001\">青岛</option>\r\n");
      out.write("\t\t<option value=\"BJ001\">北京</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr> \r\n");
      out.write("<td class=\"td_x_bg\">初始worker数:</td><td class=\"td_bg\"> <input id=\"workNum\" type=\"text\" name=\"workNum\"  value=\"\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr> \r\n");
      out.write("<td class=\"td_x_bg\">作业文件:</td><td class=\"td_bg\"> <input type=\"file\" name=\"topFile\" id=\"topFile\"/><font size=\"1\" color=\"red\">名称不能含有下划线'_'</font></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr> \r\n");
      out.write("<td class=\"td_x_bg\">作业描述:</td><td class=\"td_bg\"> <textarea id=\"desc\"  maxlength=\"35\" rows=\"6\" cols=\"35\" name=\"desc\"></textarea></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=\"2\" align=\"center\">\r\n");
      out.write("   <input align=\"right\" id=\"applyBut\" type=\"button\" value=\"提交\"  onclick=\"apply()\" style=\"width: 60px; height: 30px;border:1px solid #29598D;cursor: pointer\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
