/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-08-11 07:20:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class showAllxmlconfig_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Admin查看日志信息</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link href=\"/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/dist/css/bootstrap-select.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\"><font\r\n");
      out.write("\t\t\t\t\t\t\tsize=\"+3\">Admin</font></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"/admin/listloginfosimple\"><font size=\"+3\">已建日志</font></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div><label class=\"col-sm-2 control-label\" >用户：<a href=\"/userinfo/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user['username']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user[\"name\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a></label></div>\r\n");
      out.write("\t<!--------------------------------------------------台头 --------------------------------------------------------->\r\n");
      out.write("\t<table class=\"table table-striped\">\r\n");
      out.write("\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><font size=\"+3\">配置文件：</font></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t   <tr>\r\n");
      out.write("\t\t  <td>\r\n");
      out.write("\t\t      <table>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <label style=\"width: 200px;\" class=\"col-sm-2 control-label\">logparser.xml</label>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <textarea cols=\"70\" rows=\"20\" disabled=disabled class=\"form-control\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${xmlconf.logparserxml}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t      </table>\r\n");
      out.write("\t\t  </td>\r\n");
      out.write("\t\t    <td>\r\n");
      out.write("\t\t      <table>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <label style=\"width: 200px;\" class=\"col-sm-2 control-label\">emit.conf.bj</label>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <textarea cols=\"70\" rows=\"20\" disabled=disabled class=\"form-control\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${xmlconf.emitconfbj}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t      </table>\r\n");
      out.write("\t\t  </td>\r\n");
      out.write("\t\t    <td>\r\n");
      out.write("\t\t      <table>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <label style=\"width: 200px;\" class=\"col-sm-2 control-label\">emit.conf.sh</label>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <textarea cols=\"70\" rows=\"20\" disabled=disabled class=\"form-control\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${xmlconf.emitconfsh}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t      </table>\r\n");
      out.write("\t\t  </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t  <td>\r\n");
      out.write("\t\t      <table>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <label style=\"width: 200px;\" class=\"col-sm-2 control-label\">emit.conf.wh</label>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <textarea cols=\"70\" rows=\"20\" disabled=disabled class=\"form-control\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${xmlconf.emitconfwh}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t      </table>\r\n");
      out.write("\t\t  </td>\r\n");
      out.write("\t\t    <td>\r\n");
      out.write("\t\t      <table>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <label style=\"width: 200px;\" class=\"col-sm-2 control-label\">emit.conf.qd</label>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <textarea cols=\"70\" rows=\"20\" disabled=disabled class=\"form-control\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${xmlconf.emitconfqd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t      </table>\r\n");
      out.write("\t\t  </td>\r\n");
      out.write("\t\t    <td>\r\n");
      out.write("\t\t      <table>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <label style=\"width: 200px;\" class=\"col-sm-2 control-label\">emit.conf.gd</label>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <textarea cols=\"70\" rows=\"20\" disabled=disabled class=\"form-control\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${xmlconf.emitconfgd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t      </table>\r\n");
      out.write("\t\t  </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t   <tr>\r\n");
      out.write("\t\t <td>\r\n");
      out.write("\t\t      <table>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <label style=\"width: 200px;\" class=\"col-sm-2 control-label\">store.conf</label>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t            <td>\r\n");
      out.write("\t\t               <textarea cols=\"70\" rows=\"20\" disabled=disabled class=\"form-control\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${xmlconf.storeconf}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t         </tr>\r\n");
      out.write("\t\t      </table>\r\n");
      out.write("\t\t  </td>\r\n");
      out.write("\t\t  <td></td>\r\n");
      out.write("\t\t  <td></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td><a href=\"/admin/listloginfosimple\">返回首页</a></td></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("<!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("<script src=\"/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/dist/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\r\n");
      out.write("//下拉菜单\r\n");
      out.write("$('.selectpicker').selectpicker({noneSelectedText:'请选择'});\r\n");
      out.write("$('.selectpicker').selectpicker('val',$('.selectpicker').attr('value'));\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
