/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-02 03:59:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.monitor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.youku.dpm.utils.BasePathUtil;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

	response.setHeader("Pragma","No-cache"); 
	response.setHeader("Cache-Control","no-cache"); 
	response.setDateHeader("Expires", 0); 
	String basePath = BasePathUtil.getBasePath(request);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <title>menu frame</title>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/JQuery_zTree_v3.0/js/jquery.ztree.core-3.0.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/JQuery_zTree_v3.0/css/zTreeStyle/zTreeStyle.css\" type=\"text/css\">\r\n");
      out.write("    <LINK href=\"");
      out.print(basePath);
      out.write("common/css/admin.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("  \t<style>\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t\tbackground-color: white;\r\n");
      out.write("\t\t\tmargin:0; padding:0;\r\n");
      out.write("\t\t\ttext-align: left;\r\n");
      out.write("\t\t}\r\n");
      out.write(" \t </style>\r\n");
      out.write("  \t<script type=\"text/javascript\" >\r\n");
      out.write("\t\tvar zTree;\r\n");
      out.write("\t\tvar menuIframe;\r\n");
      out.write("\r\n");
      out.write("\t\tvar setting = {\r\n");
      out.write("\t\t\tview: {\r\n");
      out.write("\t\t\t\tdblClickExpand: false,\r\n");
      out.write("\t\t\t\tshowLine: true,\r\n");
      out.write("\t\t\t\tselectedMulti: false,\r\n");
      out.write("\t\t\t\texpandSpeed: ($.browser.msie && parseInt($.browser.version)<=6)?\"\":\"fast\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\tsimpleData: {\r\n");
      out.write("\t\t\t\t\tenable:true,\r\n");
      out.write("\t\t\t\t\tidKey: \"id\",\r\n");
      out.write("\t\t\t\t\tpIdKey: \"pId\",\r\n");
      out.write("\t\t\t\t\trootPId: \"\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcallback: {\r\n");
      out.write("\t\t\t\tbeforeClick: function(treeId, treeNode) {\r\n");
      out.write("\t\t\t\t\tvar zTree = $.fn.zTree.getZTreeObj(\"tree\");\r\n");
      out.write("\t\t\t\t\tif (treeNode.isParent) {\r\n");
      out.write("\t\t\t\t\t\tzTree.expandNode(treeNode);\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tmenuIframe.attr(\"src\",treeNode.file + \".html\");\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//var zNodes =[\r\n");
      out.write("\t\t//\t{id:1, pId:0, name:\"用户管理\", open:true},\r\n");
      out.write("\t\t//\t{id:101, pId:1, name:\"用户审核\", url:\"test1.jsp\",target:\"main_frame\"},\r\n");
      out.write("\t\t//\t{id:102, pId:1, name:\"用户列表\", url:\"test2.jsp\",target:\"main_frame\"},\r\n");
      out.write("\t\t//\t{id:103, pId:1, name:\"密码修改\", url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user!testPage.action?testBo.id=1\",target:\"main_frame\"},\r\n");
      out.write("\t\t//\t{id:104, pId:1, name:\"下载keytab\", url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user!getUncheckUserList.action\",target:\"main_frame\"},\r\n");
      out.write("\t\t//\t{id:2, pId:0, name:\"用户组管理\", open:false},\r\n");
      out.write("\t\t//\t{id:201, pId:2, name:\"更改用户组\", url:\"test1.jsp\",target:\"main_frame\"}\r\n");
      out.write("\t\t//];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t    //var menuNodes =eval(document.getElementById(\"menuStrId\").value);\r\n");
      out.write("\t\t    var menuNodes;\r\n");
      out.write("\t\t    $.post(\"");
      out.print(basePath);
      out.write("initMenu\",function(data){\r\n");
      out.write("\t\t    \tmenuNodes = data;\r\n");
      out.write("\t\t    \tvar t = $(\"#tree\");\r\n");
      out.write("\t\t\t\tt = $.fn.zTree.init(t, setting, menuNodes);\r\n");
      out.write("\t\t\t\tmenuIframe = $(\"#testIframe\");\r\n");
      out.write("\t\t\t\tmenuIframe.bind(\"load\", loadReady);\r\n");
      out.write("\t\t\t\tvar zTree = $.fn.zTree.getZTreeObj(\"tree\");\r\n");
      out.write("\t\t\t\tzTree.selectNode(zTree.getNodeByParam(\"id\", 101));\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction loadReady() {\r\n");
      out.write("\t\t\tvar bodyH = menuIframe.contents().find(\"body\").get(0).scrollHeight,\r\n");
      out.write("\t\t\thtmlH = menuIframe.contents().find(\"html\").get(0).scrollHeight,\r\n");
      out.write("\t\t\tmaxH = Math.max(bodyH, htmlH), minH = Math.min(bodyH, htmlH),\r\n");
      out.write("\t\t\th = menuIframe.height() >= maxH ? minH:maxH ;\r\n");
      out.write("\t\t\tif (h < 530) h = 530;\r\n");
      out.write("\t\t\tmenuIframe.height(h);\r\n");
      out.write("\t\t}\r\n");
      out.write("  </script>\r\n");
      out.write(" </head>\r\n");
      out.write("  <body background=\"");
      out.print(basePath);
      out.write("common/images/menu_bg.jpg\">\r\n");
      out.write("\t\t<ul id=\"tree\" class=\"ztree\" style=\"width:260px; overflowover:auto;overflow-x:no; \"></ul>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
